"""
sr_capuf_driver.py
==================

PYNQ-side driver for the Hybrid SR-CAPUF overlay.

This module provides a high-level class `SRCAPUFDriver` that:
  * loads the bit/hwh overlay
  * writes an optional random seed into the BRAM (post-Fix 1)
  * optionally reads the seed back (post-Fix 1)
  * issues challenges, collects responses, and handles the done handshake
    (post-Fix 2) or, if done is stuck, falls back to a fixed-cycle wait
  * provides both a single `query()` and a fast `query_batch()`

Hardware register map (from the Vivado block design you provided):
  axi_gpio_0 @ 0x4120_0000
      ch1 (offset 0x00): 32-bit out -> challenge[31:0]
      ch2 (offset 0x08): 1-bit  out -> trigger
  axi_gpio_1 @ 0x4121_0000
      ch1 (offset 0x00): 1-bit  in  <- response
      ch2 (offset 0x08): 1-bit  in  <- done

Post-Fix 1 additional:
  axi_bram_ctrl_0 @ 0x4000_0000  (4 KB)
      dword 0 <-> bram_seed (only dword 0 is read by the PL in v1;
      future wider seeds will extend here)

Typical usage::

    from sr_capuf_driver import SRCAPUFDriver
    drv = SRCAPUFDriver(bitfile='/home/xilinx/overlays/sr_capuf.bit')
    drv.provision_seed()                 # writes a random 32-bit seed
    seed = drv.read_seed()               # may return None on pre-Fix hw
    r_vote, r_rel, raw = drv.query(0xDEADBEEF, repeats=11)

The driver is intentionally self-contained and does not depend on
anything inside the Overlay's autogenerated MMIO dictionaries, because
names vary across Vivado versions. We use raw physical-address MMIO via
pynq.MMIO, which is stable.
"""

from __future__ import annotations

import os
import time
import hashlib
import secrets
import warnings
from typing import Optional, Tuple

import numpy as np

try:
    from pynq import Overlay, MMIO
except ImportError:  # pragma: no cover - only importable on PYNQ
    Overlay = None
    MMIO = None


# ---------------------------------------------------------------------
# Register map constants
# ---------------------------------------------------------------------

# AXI GPIO (Xilinx pg144): offset 0x00 is GPIO_DATA (ch1), 0x08 is GPIO2_DATA (ch2)
AXI_GPIO0_BASE = 0x41200000
AXI_GPIO1_BASE = 0x41210000
AXI_BRAM_BASE  = 0x40000000
AXI_BRAM_SIZE  = 0x1000  # 4 KB

GPIO_CH1_OFFSET = 0x00
GPIO_CH2_OFFSET = 0x08


# ---------------------------------------------------------------------
# Driver class
# ---------------------------------------------------------------------

class SRCAPUFDriver:
    """Thin wrapper around the SR-CAPUF overlay.

    Parameters
    ----------
    bitfile : str
        Path to the `.bit` file. The corresponding `.hwh` must be next
        to it with the same base name.
    cycle_ns : float
        FPGA clock period in nanoseconds. Used only for the fallback
        fixed-cycle wait when the `done` handshake is broken.
    fixed_wait_cycles : int
        Number of clock cycles to wait after trigger when the `done`
        line is not usable. 40 cycles at 100 MHz = 400 ns, plenty for
        the post-Fix state machine (~30 cycles worst case).
    """

    def __init__(
        self,
        bitfile: str = "/home/xilinx/overlays/sr_capuf.bit",
        cycle_ns: float = 10.0,
        fixed_wait_cycles: int = 40,
    ):
        if Overlay is None:
            raise RuntimeError(
                "pynq is not importable on this machine. "
                "This driver must run on the PYNQ Z1 board."
            )

        if not os.path.exists(bitfile):
            raise FileNotFoundError(bitfile)
        hwh = bitfile.replace(".bit", ".hwh")
        if not os.path.exists(hwh):
            raise FileNotFoundError(
                f"Missing .hwh file alongside {bitfile} (expected {hwh})"
            )

        self.overlay = Overlay(bitfile)
        self.bitfile = bitfile
        self.cycle_ns = cycle_ns
        self.fixed_wait_s = fixed_wait_cycles * cycle_ns * 1e-9

        # Raw MMIO: stable across Vivado exports.
        self._gpio0 = MMIO(AXI_GPIO0_BASE, 0x10)
        self._gpio1 = MMIO(AXI_GPIO1_BASE, 0x10)

        self._bram: Optional[MMIO] = None
        try:
            self._bram = MMIO(AXI_BRAM_BASE, AXI_BRAM_SIZE)
            # Probe: a single read should not throw on a mapped region.
            _ = self._bram.read(0x0, 4)
            self._seed_channel_present = True
        except Exception:
            self._seed_channel_present = False
            warnings.warn(
                "AXI BRAM Controller not found at 0x40000000. "
                "Seed readback/provisioning is disabled. "
                "Apply Vivado Fix 1 to enable it.",
                RuntimeWarning,
            )

        # Initialize outputs to a known state.
        self._write_challenge(0)
        self._write_trigger(0)

    # ------------------------------------------------------------------
    # Low-level MMIO helpers
    # ------------------------------------------------------------------
    def _write_challenge(self, c32: int) -> None:
        self._gpio0.write(GPIO_CH1_OFFSET, int(c32) & 0xFFFFFFFF)

    def _write_trigger(self, t: int) -> None:
        self._gpio0.write(GPIO_CH2_OFFSET, int(t) & 0x1)

    def _read_response(self) -> int:
        return self._gpio1.read(GPIO_CH1_OFFSET) & 0x1

    def _read_done(self) -> int:
        return self._gpio1.read(GPIO_CH2_OFFSET) & 0x1

    # ------------------------------------------------------------------
    # Seed management
    # ------------------------------------------------------------------
    def provision_seed(self, seed: Optional[int] = None) -> Optional[int]:
        """Write a 32-bit seed to the PL-side BRAM.

        Returns the seed that was written, or None if the BRAM controller
        is not present in the current bitstream.

        If `seed` is None, a random 32-bit value is generated with
        `secrets.randbits(32)` (OS CSPRNG).
        """
        if not self._seed_channel_present:
            warnings.warn(
                "provision_seed() called but AXI BRAM Controller is absent; "
                "the PUF will run with whatever value Vivado initialized "
                "bram_seed to (usually 0). Apply Vivado Fix 1.",
                RuntimeWarning,
            )
            return None

        if seed is None:
            seed = secrets.randbits(32)
        self._bram.write(0x0, int(seed) & 0xFFFFFFFF)  # type: ignore[union-attr]

        # After changing the seed the sr_capuf state machine must re-sample
        # it on its reset edge. On this overlay the only reset is the
        # AXI peripheral reset, so we toggle a "soft reset" approach by
        # stalling briefly. In v2 you may wire a user-controlled reset.
        time.sleep(0.01)

        readback = self.read_seed()
        if readback is not None and readback != seed:
            warnings.warn(
                f"Seed readback mismatch: wrote 0x{seed:08X}, read 0x{readback:08X}",
                RuntimeWarning,
            )
        return seed

    def read_seed(self) -> Optional[int]:
        """Read the 32-bit seed. Returns None if BRAM is not exposed."""
        if not self._seed_channel_present:
            return None
        return self._bram.read(0x0, 4) & 0xFFFFFFFF  # type: ignore[union-attr]

    def seed_fingerprint(self) -> str:
        """Stable fingerprint of the seed for logging (hex, sha256[:16])."""
        s = self.read_seed()
        if s is None:
            return "no-seed-channel"
        return hashlib.sha256(int(s).to_bytes(4, "little")).hexdigest()[:16]

    # ------------------------------------------------------------------
    # Query primitives
    # ------------------------------------------------------------------
    def _single_query_raw(self) -> int:
        """Issue one trigger and return one response bit.

        This assumes the caller has already written the challenge. The
        protocol is:
            1. Pulse trigger high for one "write" (AXI GPIO goes high,
               FPGA sees it on next aclk edge).
            2. Either wait for `done` rising edge (post-Fix 2), or wait
               a fixed number of cycles (pre-Fix). We auto-detect.
            3. Read response.
            4. Lower trigger.
        """
        # Clear any stale done first by lowering trigger.
        self._write_trigger(0)

        # Fast path: try the done handshake with a timeout.
        t0 = time.perf_counter()
        self._write_trigger(1)
        done_ok = False
        # 1 ms timeout is >> 400 ns worst case hardware latency.
        while (time.perf_counter() - t0) < 1e-3:
            if self._read_done() == 1:
                done_ok = True
                break
        if not done_ok:
            # Fallback for pre-Fix hardware: just wait fixed time.
            time.sleep(self.fixed_wait_s)

        r = self._read_response()
        self._write_trigger(0)

        return r

    def query(self, challenge: int, repeats: int = 11
              ) -> Tuple[int, int, np.ndarray]:
        """Issue one challenge `repeats` times and return majority vote.

        Returns
        -------
        r_vote : int
            Majority-voted response (0 or 1).
        r_rel : int
            Reliability count in [0, repeats]. Count of reads that
            matched the majority vote. `repeats - r_rel` is the number
            of bit-flips across reads.
        raw : np.ndarray[uint8] shape (repeats,)
            The raw response bits in read order.
        """
        if repeats < 1:
            raise ValueError("repeats must be >= 1")
        self._write_challenge(challenge)
        # Let the challenge settle through the combinational H matrix.
        # At 100 MHz one MMIO write is already plenty, but cheap insurance:
        time.sleep(5e-7)

        raw = np.zeros(repeats, dtype=np.uint8)
        for i in range(repeats):
            raw[i] = self._single_query_raw()

        ones = int(raw.sum())
        r_vote = int(ones > (repeats // 2))
        r_rel = ones if r_vote == 1 else (repeats - ones)
        return r_vote, r_rel, raw

    def query_batch(
        self,
        challenges: np.ndarray,  # uint32, shape (N,)
        repeats: int = 11,
        progress_every: int = 10000,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Issue a batch of challenges.

        Returns
        -------
        r_vote : uint8 shape (N,)
        r_rel  : uint8 shape (N,)  (in [0, repeats])
        raw    : uint8 shape (N, repeats)
        """
        N = len(challenges)
        r_vote = np.zeros(N, dtype=np.uint8)
        r_rel = np.zeros(N, dtype=np.uint8)
        raw = np.zeros((N, repeats), dtype=np.uint8)

        t0 = time.perf_counter()
        for i in range(N):
            rv, rr, rw = self.query(int(challenges[i]), repeats=repeats)
            r_vote[i] = rv
            r_rel[i] = rr
            raw[i] = rw
            if progress_every and (i + 1) % progress_every == 0:
                elapsed = time.perf_counter() - t0
                rate = (i + 1) / elapsed
                eta = (N - i - 1) / rate
                print(f"[query_batch] {i+1}/{N}  "
                      f"rate={rate:.0f} q/s  ETA={eta/60:.1f} min", flush=True)

        return r_vote, r_rel, raw

    # ------------------------------------------------------------------
    # Diagnostics
    # ------------------------------------------------------------------
    def self_test(self) -> dict:
        """Quick sanity suite. Returns a dict of observations.

        - Checks whether response varies across challenges (non-stuck).
        - Checks whether `done` handshake is usable.
        - Checks whether the seed channel is present.
        """
        result = {
            "seed_channel_present": self._seed_channel_present,
            "seed": None,
            "seed_fingerprint": self.seed_fingerprint(),
            "done_handshake_usable": None,
            "response_variety": None,
        }
        if self._seed_channel_present:
            result["seed"] = self.read_seed()

        # Does done actually transition per query?
        transitions = 0
        for _ in range(8):
            self._write_challenge(secrets.randbits(32))
            self._write_trigger(0)
            # Wait for done to fall (if Fix 2 applied). Timeout 1 ms.
            t0 = time.perf_counter()
            while self._read_done() == 1 and (time.perf_counter() - t0) < 1e-3:
                pass
            done_low = (self._read_done() == 0)
            self._write_trigger(1)
            t0 = time.perf_counter()
            saw_rise = False
            while (time.perf_counter() - t0) < 1e-3:
                if self._read_done() == 1:
                    saw_rise = True
                    break
            self._write_trigger(0)
            if done_low and saw_rise:
                transitions += 1
        result["done_handshake_usable"] = transitions >= 6  # 6/8

        # Does the response vary?
        rs = []
        for _ in range(64):
            rv, _, _ = self.query(secrets.randbits(32), repeats=3)
            rs.append(rv)
        result["response_variety"] = (0 in rs) and (1 in rs)

        return result
